In [8]:
import sklearn

In [9]:
import sys
!{sys.executable} -m pip install scikit-learn


[notice] A new release of pip available: 22.3 -> 25.1.1
[notice] To update, run: C:\Users\MINJUN\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [10]:
import urllib
DOWNLOAD_ROOT = "https://raw.githubsercontent.com/rickiepark/handson-m12/master/"

In [11]:
import urllib
DOWNLOAD_ROOT = "https://raw.githubsercontent.com/rickiepark/handson-m12/master/"
os.makedirs(datapath, exist_ok = True)
for filename in ("oecd_bli_2015.csv","gdp_per_capita.csv"):
    print("Downloading", filename)
    url = DOWNLOAD_ROOT + "datasets/lifesat/", filename
    urllib.request.urlretrieve(url, datapath + filename)

NameError: name 'os' is not defined

In [ ]:
import os
import urllib.request

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/rickiepark/handson-ml2/master/"
datapath = "datasets/lifesat/"
os.makedirs(datapath, exist_ok=True)

for filename in ("oecd_bli_2015.csv", "gdp_per_capita.csv"):
    print("Downloading", filename)
    url = DOWNLOAD_ROOT + datapath + filename
    urllib.request.urlretrieve(url, datapath + filename)


In [ ]:
import matplotlib as mpl

mpl.rc('axes', labelsize =14)
mpl.rc('xtick', labelsize =12)
mpl.rc('ytick', labelsize =12)


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import linear_model

oecd_bli = pd.read_csv(datapath + "oecd_bli_2015.csv", thousands = ",")
oecd_bli.head(3)

In [ ]:
gdp_per_capita = pd.read_csv(
    datapath + "gdp_per_capita.csv",
    thousands=",",
    delimiter="\t",
    encoding="latin1",
    na_values="n/a"
)

gdp_per_capita.head(3)


In [ ]:
oecd_bli = oecd_bli[oecd_bli["INEQUALITY"] == "TOT"]

In [ ]:
oecd_bli.head(3)

In [12]:
oecd_bli = oecd_bli.pivot(index = "Country", columns ="Indicator", values = "Value")
oecd_bli

NameError: name 'oecd_bli' is not defined

In [13]:
gdp_per_capita.rename(columns = {"2015": "GDP per Captia" }, inplace =True)
gdp_per_capita

NameError: name 'gdp_per_capita' is not defined

In [17]:
remove_indices = [0,1,6,8,33,34,35]
keep_indices = list(set(range(36)) - set(remove_indices))
keep_indices

[2,
 3,
 4,
 5,
 7,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32]

In [18]:
country_stats = full_country_stats[["GDP per Captia", "Life satisfaction"]].iloc[keep_indices]
country_stats

NameError: name 'full_country_stats' is not defined

In [19]:
y = np.c_[country_stats["Life satisfaction"]]
y

NameError: name 'np' is not defined

In [20]:
country_stats.plot(kind = 'scatter', x = "GDP per Captia", y = "Life satisfaction")
plt.show()

NameError: name 'country_stats' is not defined

In [21]:
X = np.c_[country_stats["GDP per Captia"]]
X

NameError: name 'np' is not defined

In [22]:
from sklearn.linear_model import LinearRegression  

X = np.c_[country_stats["GDP per Captia"]]  
model = LinearRegression()                  
model.fit(X, y)
X_new = np.array([[22587]])                 
print(model.predict(X_new))               


NameError: name 'np' is not defined

In [30]:
import pandas as pd
df = pd.read_csv("boston_house.csv")
df.head(3)

AGE       B     RM     CRIM     DIS  INDUS  LSTAT    NOX  PTRATIO  RAD  \
0  65.2  396.90  6.575  0.00632  4.0900   2.31   4.98  0.538     15.3    1   
1  78.9  396.90  6.421  0.02731  4.9671   7.07   9.14  0.469     17.8    2   
2  61.1  392.83  7.185  0.02729  4.9671   7.07   4.03  0.469     17.8    2   

     ZN  TAX  CHAS  Target  
0  18.0  296     0    24.0  
1   0.0  242     0    21.6  
2   0.0  242     0    34.7

In [31]:
### 보스턴 집값 데이터
CRIM: 범죄율
INDUS: 비소매상업지역 면적 비율
NOX: 일산화질소 농도
RM: 주택당 방 수
LSTAT: 인구 중 하위 계층 비율
B: 인구 중 흑인 비율
PTRATIO: 학생/교사 비율
ZN: 25,000 평방피트를 초과 거주지역 비율
CHAS: 찰스강의 경계에 위치한 경우는 1, 아니면 0
AGE: 1940년 이전에 건축된 주택의 비율
RAD: 방사형 고속도로까지의 거리
DIS: 직업센터의 거리
TAX: 재산세율





SyntaxError: invalid decimal literal (3277408867.py, line 11)

In [32]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size = 0.3, random_state = 0)
df_train.shape, df_test.shape

((354, 14), (152, 14))

In [33]:
df_train.head(10)

AGE       B     RM      CRIM     DIS  INDUS  LSTAT    NOX  PTRATIO  \
141  100.0  396.90  5.019   1.62864  1.4394  21.89  34.41  0.624     21.2   
272   58.7  394.96  6.538   0.11460  3.9175   6.96   7.73  0.464     18.6   
135   98.2  394.67  6.335   0.55778  2.1107  21.89  16.96  0.624     21.2   
298   20.1  368.24  6.345   0.06466  7.8278   2.24   4.97  0.400     14.8   
122   92.9  378.09  5.961   0.09299  2.0869  25.65  17.93  0.581     19.1   
22    91.7  396.90  6.142   1.23247  3.9769   8.14  18.72  0.538     21.0   
68    36.8  396.90  5.594   0.13554  6.4980   6.07  13.09  0.409     18.9   
20    98.1  376.57  5.570   1.25179  3.7979   8.14  21.02  0.538     21.0   
437  100.0    9.32  6.152  15.17720  1.9142  18.10  26.45  0.740     20.2   
14    84.5  380.02  6.096   0.63796  4.4619   8.14  10.26  0.538     21.0   

     RAD    ZN  TAX  CHAS  Target  
141    4   0.0  437     0    14.4  
272    3  20.0  223     0    24.4  
135    4   0.0  437     0    18.1  
298    5  70.0  358     0    22.5  
122    2   0.0  188     0    20.5  
22     4   0.0  307     0    15.2  
68     4  12.5  345     0    17.4  
20     4   0.0  307     0    13.6  
437   24   0.0  666     0     8.7  
14     4   0.0  307     0    18.2

In [34]:
dfx = df.drop(["Target"], axis = 1)
dfx.head()

AGE       B     RM     CRIM     DIS  INDUS  LSTAT    NOX  PTRATIO  RAD  \
0  65.2  396.90  6.575  0.00632  4.0900   2.31   4.98  0.538     15.3    1   
1  78.9  396.90  6.421  0.02731  4.9671   7.07   9.14  0.469     17.8    2   
2  61.1  392.83  7.185  0.02729  4.9671   7.07   4.03  0.469     17.8    2   
3  45.8  394.63  6.998  0.03237  6.0622   2.18   2.94  0.458     18.7    3   
4  54.2  396.90  7.147  0.06905  6.0622   2.18   5.33  0.458     18.7    3   

     ZN  TAX  CHAS  
0  18.0  296     0  
1   0.0  242     0  
2   0.0  242     0  
3   0.0  222     0  
4   0.0  222     0

In [35]:
dfy = df[["Target"]]
dfy.head()

Target
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2

In [36]:
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(dfx,dfy, test_size = 0.3, random_state = 0)
dfX_train.shape, dfX_test.shape, dfy_train.shape, dfy_test.shape

((354, 13), (152, 13), (354, 1), (152, 1))

In [37]:
from sklearn.model_selection import KFold
# statsmodels : 통계적 모델링, 통계 테스트, 데이터 탐색 및 시각화를 지원하는 라이브러리
import statsmodels.api as sm
import numpy as np

In [38]:
scores = np.zeros(5)
scores

array([0., 0., 0., 0., 0.])

In [39]:
cv = KFold(5, shuffle= True,random_state=0)
cv

KFold(n_splits=5, random_state=0, shuffle=True)

In [40]:
feature_names = df.columns[:-1]
print(feature_names)

Index(['AGE', 'B', 'RM', 'CRIM', 'DIS', 'INDUS', 'LSTAT', 'NOX', 'PTRATIO',
       'RAD', 'ZN', 'TAX', 'CHAS'],
      dtype='object')


In [43]:
for i, (idx_train, idx_test) in enumerate(cv.split(df)):
    df_train = df.iloc[idx_train]
    df_test = df.iloc[idx_test]

    model = sm.OLS.from_formula("Target~" + "+".join(feature_names),data= df_train)
    result = model.fit()

    pred = result.predict(df_test)
    rss = ((df_test.Target - pred) ** 2).sum() #정확도?
    tss = ((df_test.Target - df_test.Target.mean()) ** 2).sum()
    rsquared = 1 - rss/tss

    scores[i] = rsquared
    print("학습 R2 = {:.8f},검증 R2 = {:.8f}".format(result.rsquared, rsquared))

학습 R2 = 0.77301356,검증 R2 = 0.58922238
학습 R2 = 0.72917058,검증 R2 = 0.77799144
학습 R2 = 0.74897081,검증 R2 = 0.66791979
학습 R2 = 0.75658611,검증 R2 = 0.66801630
학습 R2 = 0.70497483,검증 R2 = 0.83953317


In [45]:
from sklearn.metrics import r2_score #결정계수
for i, (idx_train, idx_test) in enumerate(cv.split(df)):
    df_train = df.iloc[idx_train]
    df_test = df.iloc[idx_test]

    model = sm.OLS.from_formula("Target~" + "+".join(feature_names),data= df_train)
    result = model.fit()

    pred = result.predict(df_test)
    rsuared = r2_score(df_test.Target, pred)
    scores[i] = rsquared
    print("학습 R2 = {:.8f},검증 R2 = {:.8f}".format(result.rsquared, rsquared))

학습 R2 = 0.77301356,검증 R2 = 0.83953317
학습 R2 = 0.72917058,검증 R2 = 0.83953317
학습 R2 = 0.74897081,검증 R2 = 0.83953317
학습 R2 = 0.75658611,검증 R2 = 0.83953317
학습 R2 = 0.70497483,검증 R2 = 0.83953317


In [49]:
from sklearn.base import BaseEstimator, RegressorMixin
import statsmodels.formula.api as smf
import pandas as pd

class StatsmodelOLS(BaseEstimator, RegressorMixin):
    def __init__(self, formula):
        self.formula = formula
        self.model = None
        self.data = None
        self.result = None

    def fit(self, dfX, dfy):
        self.data = pd.concat([dfX, dfy], axis=1)
        self.model = smf.ols(self.formula, data=self.data)
        self.result = self.model.fit()
        return self

    def predict(self, new_data):
        return self.result.predict(new_data)


In [53]:
from sklearn.model_selection import cross_val_score, KFold

model = StatsmodelOLS("Target ~ " + " + ".join(feature_names))
cv = KFold(n_splits=5, shuffle=True, random_state=0)

scores = cross_val_score(model, dfX, dfy, scoring="r2", cv=cv)
print("R2 scores for each fold:", scores)
print("Average R2 score:", scores.mean())


NameError: name 'dfX' is not defined

In [54]:
import pandas as pd
import seaborn as sns
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import r2_score
import statsmodels.formula.api as smf

# 사용자 정의 회귀 클래스
class StatsmodelOLS(BaseEstimator, RegressorMixin):
    def __init__(self, formula):
        self.formula = formula
        self.model = None
        self.data = None
        self.result = None

    def fit(self, dfX, dfy):
        # dfy가 Series면 DataFrame으로 변환
        if isinstance(dfy, pd.Series):
            dfy = dfy.to_frame()
        self.data = pd.concat([dfX, dfy], axis=1)
        self.model = smf.ols(self.formula, data=self.data)
        self.result = self.model.fit()
        return self

    def predict(self, new_data):
        return self.result.predict(new_data)

    def score(self, X, y):
        y_pred = self.predict(X)
        return r2_score(y, y_pred)

# 예제 데이터 로딩
df = sns.load_dataset('tips')

# 변수 설정
feature_names = ['total_bill', 'size']
dfX = df[feature_names]
dfy = df['tip']  # 종속변수

# 모델 정의
formula = "tip ~ total_bill + size"
model = StatsmodelOLS(formula)

# 교차검증
cv = KFold(n_splits=5, shuffle=True, random_state=0)
scores = cross_val_score(model, dfX, dfy, scoring="r2", cv=cv)

# 결과 출력
print("R2 scores for each fold:", scores)
print("Average R2 score:", scores.mean())


R2 scores for each fold: [0.59315389 0.24430195 0.51288284 0.33161029 0.38003728]
Average R2 score: 0.4123972473838496


In [55]:
import seaborn as sns

iris = sns.load_dataset("iris")
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [58]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import scale
import pandas as pd

# Iris 데이터 로드
iris = load_iris()
x = iris.data  # 특성 데이터 (numpy array)
y = iris.target  # 레이블

# 표준화 (평균 0, 표준편차 1)
x_scaled = scale(x)

# 결과 보기 (앞 5개 행)
print(x_scaled[:5, :])

# pandas DataFrame으로 변환 (선택사항)
x_scaled_df = pd.DataFrame(x_scaled, columns=iris.feature_names)
print(x_scaled_df.head())


[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444


In [63]:
from sklearn.preprocessing import minmax_scale

iris_minmax_scaled = minmax_scale(x)
iris_minmax_scaled[:5,:]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [64]:
from sklearn.preprocessing import maxabs_scale

In [65]:
iris_maxabs_scaled = maxabs_scale(x)

In [66]:
iris_maxabs_scaled[:5,:]

array([[0.64556962, 0.79545455, 0.20289855, 0.08      ],
       [0.62025316, 0.68181818, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.58227848, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.81818182, 0.20289855, 0.08      ]])

In [69]:
import seaborn as sns

iris = sns.load_dataset("iris")
iris.iloc[:5, :-1]

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [72]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

# iris 데이터 로드
iris_raw = load_iris()
iris = pd.DataFrame(iris_raw.data, columns=iris_raw.feature_names)
iris['target'] = iris_raw.target  # 마지막 열로 레이블 추가

# 표준화
sc = StandardScaler()
sc.fit(iris.iloc[:, :-1])  # 특성 부분만 fit
iris_scaled = sc.transform(iris.iloc[:, :-1])  # transform 적용

# 결과 출력
print(iris_scaled[:5, :])


[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [73]:
iris_origin = sc.inverse_transform(iris_scaled)
iris_origin[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [76]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

iris = sns.load_dataset("iris")
y = iris.species
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [77]:
le = LabelEncoder()
le.fit(y)
species = le.transform(y)
species

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
le.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [80]:
species = le.inverse_transform(species)
species

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [85]:
onehot = pd.get_dummies(species)

# 결과 출력
print(onehot)

     setosa  versicolor  virginica
0      True       False      False
1      True       False      False
2      True       False      False
3      True       False      False
4      True       False      False
..      ...         ...        ...
145   False       False       True
146   False       False       True
147   False       False       True
148   False       False       True
149   False       False       True

[150 rows x 3 columns]


In [83]:
from sklearn.preprocessing import OneHotEncoder


enc = OneHotEncoder()
enc.fit(species.reshape(-1,1))

OneHotEncoder()

In [89]:
iris_onehot = enc.transform(species.reshape(-1,1))
iris_onehot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 150 stored elements and shape (150, 3)>

In [104]:
print(iris_onehot)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 150 stored elements and shape (150, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (125, 2)	1.0
  (126, 2)	1.0
  (127, 2)	1.0
  (128, 2)	1.0
  (129, 2)	1.0
  (130, 2)	1.0
  (131, 2)	1.0
  (132, 2)	1.0
  (133, 2)	1.0
  (134, 2)	1.0
  (135, 2)	1.0
  (136, 2)	1.0
  (137, 2)	1.0
  (138, 2)	1.0
  (139, 2)	1.0
  (140, 2)	1.0
  (141, 2)	1.0
  (142, 2)	1.0
  (143, 2)	1.0
  (144, 2)	1.0
  (145, 2)	1.0
  (146, 2)	1.0
  (147, 2)	1.0
  (148, 2)	1.0
  (149, 2)	1.0


In [105]:
iris_onehot.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [106]:
import seaborn as sns
iris = sns.load_dataset("iris")
x = iris.iloc[:,:-1]
x[0:5]

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [98]:
import random
for col in range(4):
    x.iloc[[random.sample(range(len(iris)), 10)], col] = float('nan')
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           NaN          3.5           1.4          NaN
1           NaN          3.0           NaN          NaN
2           4.7          3.2           NaN          0.2
3           4.6          3.1           NaN          0.2
4           5.0          3.6           1.4          0.2

In [100]:
x.mean(axis = 0)

sepal_length    5.910714
sepal_width     3.058407
petal_length    3.672973
petal_width     1.202632
dtype: float64

In [103]:
from sklearn.impute import SimpleImputer
import numpy as np

imp_mean = SimpleImputer(missing_values = np.nan, strategy = "mean" )
imp_mean.fit_transform(x)[0:5, :]

array([[5.91071429, 3.5       , 1.4       , 1.20263158],
       [5.91071429, 3.        , 3.67297297, 1.20263158],
       [4.7       , 3.2       , 3.67297297, 0.2       ],
       [4.6       , 3.1       , 3.67297297, 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ]])