In [73]:
from keras.models import Sequential
from keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_shape = (2, 10)))
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_9 (SimpleRNN)    (None, 3)                 42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [74]:
from keras.models import Sequential
from keras.layers import SimpleRNN
import numpy as np

imputs = np.random.random((8,2,10)) #batch size, time-stemp , input

model = Sequential()
model.add(SimpleRNN(3))
model(imputs)
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_10 (SimpleRNN)   (8, 3)                    42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [75]:
from keras.models import Sequential
from keras.layers import SimpleRNN
import numpy as np

imputs = np.random.random((8,2,10)) #batch size, time-stemp , input

model = Sequential()
model.add(SimpleRNN(3, return_sequences = True))
model(imputs)
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_11 (SimpleRNN)   (8, 2, 3)                 42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [76]:
### RNN을 이용하여 텍스트 생성하기

In [77]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [78]:
text = """경마장에 있는 말이 뛰고 있다\n그의 말이 법이다\n가는 말이 고아야 오는 말이 곱다"""

In [79]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print("단어 집합의 크기: %d" % vocab_size)

단어 집합의 크기: 12


In [80]:
t.word_index

{'말이': 1,
 '경마장에': 2,
 '있는': 3,
 '뛰고': 4,
 '있다': 5,
 '그의': 6,
 '법이다': 7,
 '가는': 8,
 '고아야': 9,
 '오는': 10,
 '곱다': 11}

In [81]:
sequences = list()
for line in text.split("\n"):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print(sequences)
print("학습에 사용할 샘플의 개수: %d" % len(sequence))

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]
학습에 사용할 샘플의 개수: 6


In [82]:
max_len = max(len(l) for l in sequences)
print("샘플의 최대 길이: {}".format(max_len))

샘플의 최대 길이: 6


In [83]:
sequences = pad_sequences(sequences, maxlen =max_len, padding= 'pre')
sequences

array([[ 0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  2,  3,  1],
       [ 0,  0,  2,  3,  1,  4],
       [ 0,  2,  3,  1,  4,  5],
       [ 0,  0,  0,  0,  6,  1],
       [ 0,  0,  0,  6,  1,  7],
       [ 0,  0,  0,  0,  8,  1],
       [ 0,  0,  0,  8,  1,  9],
       [ 0,  0,  8,  1,  9, 10],
       [ 0,  8,  1,  9, 10,  1],
       [ 8,  1,  9, 10,  1, 11]])

| 파라미터         | 설명                                                   | 예시                                                    |
| ------------ | ---------------------------------------------------- | ----------------------------------------------------- |
| `sequences`  | 패딩할 대상 시퀀스 (리스트의 리스트)                                | `[[1, 2, 3], [4, 5], [6]]`                            |
| `maxlen`     | 최종적으로 맞출 시퀀스 길이<br>지정 안 하면 가장 긴 시퀀스 기준               | `maxlen=4` → `[0, 1, 2, 3]`                           |
| `dtype`      | 데이터 타입 (기본 `'int32'`)                                | 보통 그대로 둠                                              |
| `padding`    | 짧은 시퀀스를 어디에 0으로 채울지 <br> `'pre'` (앞에), `'post'` (뒤에) | `'pre'` → `[0, 0, 1, 2]`<br>`'post'` → `[1, 2, 0, 0]` |
| `truncating` | 길이를 자를 때 앞/뒤 중 어디를 자를지                               | `'pre'` → 앞에서 자름<br>`'post'` → 뒤에서 자름                 |
| `value`      | 패딩할 때 넣을 값 (기본: `0`)                                 | `value=-1` → `[-1, -1, 1, 2]`                         |


In [84]:
sequences = [[3, 4, 5], [1, 2], [6]]
max_len = 4
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [85]:
sequences = np.array(sequences)
X = sequences[:, : -1]
y = sequences[:, -1]

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size ,6))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, actication = 'softmax')
model.build(input_shape=(None,))

In [86]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 4


In [87]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [88]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [89]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [90]:
model = Sequential()
model.add(Embedding(vocab_size, 6)) # 밀집벡터
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.build(input_shape=(None, max_len-1))
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 6)           72        
                                                                 
 simple_rnn_12 (SimpleRNN)   (None, 32)                1248      
                                                                 
 dense_3 (Dense)             (None, 12)                396       
                                                                 
Total params: 1716 (6.70 KB)
Trainable params: 1716 (6.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [94]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 0.2001 - accuracy: 1.0000 - 728ms/epoch - 728ms/step
Epoch 2/200
1/1 - 0s - loss: 0.1961 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 3/200
1/1 - 0s - loss: 0.1923 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 4/200
1/1 - 0s - loss: 0.1884 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
Epoch 5/200
1/1 - 0s - loss: 0.1847 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 6/200
1/1 - 0s - loss: 0.1810 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
Epoch 7/200
1/1 - 0s - loss: 0.1773 - accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 8/200
1/1 - 0s - loss: 0.1737 - accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 9/200
1/1 - 0s - loss: 0.1702 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
Epoch 10/200
1/1 - 0s - loss: 0.1667 - accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 11/200
1/1 - 0s - loss: 0.1632 - accuracy: 1.0000 - 5ms/epoch - 5ms/step
Epoch 12/200
1/1 - 0s - loss: 0.1598 - accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 13/200
1/1 - 0s - loss: 0.1565 - accuracy: 1.0000 -

In [95]:
def sentence_generation(model, t, current_word, n ):
    init_word = current_word
    sentence =''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen = max_len -1 , padding= 'pre')
        temp = model.predict(encoded)
        result = np.argmax(temp, axis = 1)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + " " +word
        sentence = sentence + ' ' + word
    sentence =init_word + sentence
    return sentence

In [100]:
print(sentence_generation(model, t, "경마장에", 3))

1/1 [==============================] - 0s 14ms/step
경마장에 경마장에 있다 있다


In [101]:
#LSTM을 이용하여 텍스트 생성하기

In [103]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [105]:
df = pd.read_csv("./ArticleApril2018.csv")
df.head(2)

FileNotFoundError: [Errno 2] No such file or directory: './ArticleApril2018.csv'